const routes = {
    home: '/',
    detailType: '/type/:roomId/:hotelId',
    detailHotel: '/hotel/:id',
    detailBranch: '/branch/:id',
    checkout: '/checkout',
    checkin: '/checkin/:bookingCode',
    signin: '/signin',
    signup: '/signup',
    profile: '/profile/:id',
    history: '/history/:id',
    setting: '/setting/:id',
    upload: '/upload',
    earning: '/earning',
    rooms: '/rooms',
    roomTypes: '/room-types',
    services: '/services',
    dashboard: '/dashboard',
};
export default routes